[package]
name = "listen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossbeam = "0.8.4"
prometheus = "0.13.3"
reqwest = { version = "0.12.4", features = ["json"] }
serde = "1.0.199"
serde_json = "1.0.116"
solana-account-decoder = "1.18.12"
solana-client = "1.18.12"
solana-sdk = "1.18.12"
solana-transaction-status = "1.18.12"
tokio = { version = "1.37.0", features = ["full"] }
tokio-test = "0.4.4"
