services:
  listener:
    image: piotrostr/listen
    ports:
      - "8078:8078"
    volumes:
      - ./.env:/.env
    command: ["listen", "listener-service", "--webhook"]
    environment:
      - CHECKER_URL=http://checker:8079
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: listener
    depends_on:
      - fluentd
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
  checker:
    image: piotrostr/listen
    ports:
      - "8079:8079"
    volumes:
      - ./.env:/.env
    command: ["listen", "checker-service"]
    environment:
      - BUYER_URL=http://buyer:8080
    restart: always
    deploy:
      replicas: 5
      mode: replicated
      endpoint_mode: vip
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: checker
    depends_on:
      - fluentd
  buyer:
    image: piotrostr/listen
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
      - ./auth.json:/auth.json
      - ./fund.json:/fund.json
    command: ["listen", "buyer-service"]
    restart: always
    environment:
      - SELLER_URL=http://seller:8081
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: buyer
    depends_on:
      - fluentd
    deploy:
      replicas: 3
      mode: replicated
      endpoint_mode: vip
  seller:
    image: piotrostr/listen
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/.env
      - ./auth.json:/auth.json
      - ./fund.json:/fund.json
    command: ["listen", "seller-service"]
    restart: always
    deploy:
      replicas: 5
      mode: replicated
      endpoint_mode: vip
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: seller
    depends_on:
      - fluentd
  fluentd:
    image: fluent/fluentd:v1.17.0-1.0
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
