[package]
name = "stream"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.5"
futures-util = "0.3.31"
log = "0.4.22"
solana-account-decoder = "2.0.13"
solana-client = "2.0.13"
solana-sdk = "2.0.13"
tokio = { version = "1.40.0", features = ["full"] }
